
SECRET_KEY = "DAS<:WDIONIZCNISDSD_)+UWHAI"

# 数据库的配置信息
HOSTNAME = ""
PORT = 
USERNAME = ""
PASSWORD = ""
DATABAEE = ""

DB_URI = \
    f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:" \
    f"{PORT}/{DATABAEE}?charset=utf8"
SQLALCHEMY_DATABASE_URI = DB_URI


# 邮箱配置
# RHGEXLBHKWDRJFMY
MAIL_SERVER = "imap.exmail.qq.com"
MAIL_USE_SSL = True
MAIL_PORT = 465
MAIL_USERNAME = ""
MAIL_PASSWORD = ""
MAIL_DEFAULT_SENDER = "
